/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development snapshot 2015-07-28.65f3500"
#define SSHVER "PuTTY-Snapshot-2015-07-28.65f3500"
#define BINARY_VERSION 0,65,1003,0
